version: "3.8"

services:
  web:
    build: .
    environment:
      - ENVIRONMENT=docker
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run.py
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: requirements.txt