version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    restart: always
    command: python run.py
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge